# This is triggered on every push to the main branch
# and triggers a new deploy on the eol website.
name: Deploy website
on:
  # We trigger a deploy, if we've updated
  # releaselog in this push.
  push:
    branches:
      - main
    paths:
      - 'releases/*'
jobs:
  deploy:
    name: Deploy Website
    if: github.repository_owner == 'khulnasoft'
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Trigger Deploy on Netlify
      env :
        NETLIFY_HOOK_URL: '${{secrets.NETLIFY_HOOK_URL}}'
      run:
        curl -X POST -d {} "$NETLIFY_HOOK_URL"
